apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: HELLO-SERVER-CLUSTER
      http:
        paths:
          - backend:
              serviceName: some-svc
              servicePort: 8081
